### ISSUE TITLE
Readme recommendation

### ISSUE THREAD

**Issue by ghost** [aydinzaman/Py-Projects#1]
Hi, 

Thank you for your video tutorial. It's really helpful. This step was missing and I got stuck for a bit. I recommend adding it to your Readme or YouTube description:

Prerequisite is to have the Adafruit_Python_GPIO package installed:

`sudo apt-get update`
`sudo apt-get install build-essential python-pip python-dev python-smbus git`
`git clone https://github.com/adafruit/Adafruit_Python_GPIO.git`
`cd Adafruit_Python_GPIO`
`sudo python setup.py install`

**Comment by aydinzaman** [comment]
Thank you for your suggestion. I will update the readme and youtube description

**Comment by aydinzaman** [comment]
updated the readme...closing
